CI: update supported Postgres and Go versions
lib/pq pull request #1113
Opened 2023-03-22 09:41 UTC by drakkan

2023-04-14 07:39 UTC, rafiss requested changes
thank you! i just had minor comments

2023-04-14 07:39 UTC, rafiss commented on ssl_test.go
> +	if errWrapped := errors.Unwrap(err); errWrapped != nil {
could this use `errors.As` so that the test also checks that the outer error is `CertificateVerificationError`?

2023-04-14 07:39 UTC, rafiss commented on ssl_test.go
> +	if errWrapped := errors.Unwrap(err); errWrapped != nil {
and similar for here

2023-04-28 13:33 UTC, otan commented
using https://github.com/lib/pq/pull/1124

2023-04-28 13:33 UTC, closed without merging